### ISSUE TITLE
Only support opencv3.2?

### ISSUE THREAD

**Issue by davidz123** [mogvision/FFD#2]
Hi, 
   When I run the FDD binary file, it requires opencv3.2 dependency,  any other version of opencv supported?
   thx :)

**Comment by lixiaohang** [comment]
can you use the demo_FFD.py to detect feature use your own image？

**Comment by lixiaohang** [comment]
my opencv version is  3.4.2.16 and the opencv_contrib_python is 3.4.2.16 ,but I use my own image ,the FFD-master\image output do not change

**Comment by davidz123** [comment]
@lixiaohang I am trying on it. Cause I only have binary file, I have to adopt the envirenment as the building-env.
