### ISSUE TITLE
The default params are not leading to repeatable corner detections?

### ISSUE THREAD

**Issue by zehongs** [mogvision/FFD#6]
Hi, I used the default parameters, but the detected keypoints are not lying on the corner (left-up bbx) and not repeatable(bottom bbx). Did I make it wrong? 
![image](https://user-images.githubusercontent.com/25296730/103135711-1d73eb00-46f5-11eb-808a-81b9df593a0f.png)

**Comment by PengboMi** [comment]
老哥 你好  请问你是咋换成你自己的测试图像的啊？

**Comment by zehongs** [comment]
我不记得了，好像是改了他的demo文件。我已经不做这块了。

**Comment by PengboMi** [comment]
好的谢谢老哥  我自己再研究研究

**Comment by PengboMi** [comment]
老哥，您能不能把您当时改好的代码发我一下，我参考您的研究下。现在我换成自己的测试图像运行后，源代码运行并没有输出关键点的信息啊。

**Comment by PengboMi** [comment]
封装的FFD好像并没有输出KEYPOINTS坐标信息啊

**Comment by zehongs** [comment]
sorry我已经没有这份代码了，你自己看着改改

**Comment by PengboMi** [comment]
好的
