### ISSUE TITLE
How to use this project to detect my own png image?

### ISSUE THREAD

**Issue by a694654760** [mogvision/FFD#7]
Missing .txt file
Can .txt files be generated by programs? But I think it’s the keypoint of information. How to generate it, I can't find it.
I hope that the brothers who have seen can answer it, I am really a novice.
Thank you !

**Comment by yatouxingren** [comment]
i alse have this error
Traceback (most recent call last):
  File "demo_FFD.py", line 69, in <module>
    keypoints, num_kp = readkp(os.path.join(store_dir, 'FFD_'+image_name+'.txt'))
  File "D:\2021\Q2\FFD-master\util\util.py", line 16, in readkp
    with open(filename, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\2021\\Q2\\FFD-master\\myimage\\FFD_test1.png.txt'

**Comment by PengboMi** [comment]
me too

**Comment by 1061700625** [comment]
大家可以参考：https://github.com/mogvision/FFD/issues/8#issuecomment-961601740

**Comment by a694654760** [comment]
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mogvision/FFD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 中午11:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mogvision/FFD] How to use this project to detect my own png image? (#7)





 
大家可以参考：#8 (comment)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PengboMi** [comment]
牛啊，感谢
